export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const DOWNLOAD_SONG_REQUEST = 'DOWNLOAD_SONG_REQUEST';
export const DOWNLOAD_SONG_SUCCESS = 'DOWNLOAD_SONG_SUCCESS';
export const DOWNLOAD_SONG_FAILURE = 'DOWNLOAD_SONG_FAILURE';

export const SET_SONG_AND_LIST = 'SET_SONG_AND_LIST';
export const PLAY_MUSIC = 'PLAY_MUSIC';
export const STOP_MUSIC = 'STOP_MUSIC';
export const PAUSE_MUSIC = 'PAUSE_MUSIC';
export const NEXT_SONG = 'NEXT_SONG';
export const PREVIOUS_SONG = 'PREVIOUS_SONG';
export const LOOP_SONG = 'LOOP_SONG';
export const SET_AUDIO = 'SET_AUDIO';
export const SET_SRC = 'SET_SRC';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_USER_VOLUME= 'SET_USER_VOLUME';

export const GET_SONGLIST_REQUEST = 'GET_SONGLIST_REQUEST';
export const GET_SONGLIST_SUCCESS = 'GET_SONGLIST_SUCCESS';
export const GET_SONGLIST_FAILURE = 'GET_SONGLIST_FAILURE';

export const ADD_PLAYLIST_REQUEST = 'ADD_PLAYLIST_REQUEST';
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_FAILURE = 'ADD_PLAYLIST_FAILURE';